# Generated by Django 5.2.2 on 2025-10-08 00:01

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BasketballStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_name", models.CharField(max_length=200)),
                ("team_name", models.CharField(max_length=100)),
                ("season", models.CharField(max_length=9)),
                ("games_played", models.IntegerField(blank=True, null=True)),
                ("points_per_game", models.FloatField(blank=True, null=True)),
                ("field_goal_percentage", models.FloatField(blank=True, null=True)),
                ("three_point_percentage", models.FloatField(blank=True, null=True)),
                ("free_throw_percentage", models.FloatField(blank=True, null=True)),
                ("rebounds_per_game", models.FloatField(blank=True, null=True)),
                ("assists_per_game", models.FloatField(blank=True, null=True)),
                ("steals_per_game", models.FloatField(blank=True, null=True)),
                ("blocks_per_game", models.FloatField(blank=True, null=True)),
                ("turnovers_per_game", models.FloatField(blank=True, null=True)),
                ("minutes_per_game", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="FootballStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_name", models.CharField(max_length=200)),
                ("team_name", models.CharField(max_length=100)),
                ("position", models.CharField(blank=True, max_length=10, null=True)),
                ("season", models.CharField(max_length=9)),
                ("games_played", models.IntegerField(blank=True, null=True)),
                ("passing_yards", models.IntegerField(blank=True, null=True)),
                ("passing_touchdowns", models.IntegerField(blank=True, null=True)),
                ("interceptions_thrown", models.IntegerField(blank=True, null=True)),
                ("rushing_yards", models.IntegerField(blank=True, null=True)),
                ("rushing_touchdowns", models.IntegerField(blank=True, null=True)),
                ("receiving_yards", models.IntegerField(blank=True, null=True)),
                ("receiving_touchdowns", models.IntegerField(blank=True, null=True)),
                ("total_tackles", models.IntegerField(blank=True, null=True)),
                ("sacks", models.FloatField(blank=True, null=True)),
                ("interceptions", models.IntegerField(blank=True, null=True)),
                ("fumbles_recovered", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ScrapedData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_url", models.URLField(max_length=500)),
                ("data_type", models.CharField(max_length=100)),
                ("season", models.CharField(max_length=9)),
                ("raw_data", models.JSONField()),
                ("processed_data", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("scraped_at", models.DateTimeField()),
                ("source", models.CharField(max_length=100)),
                ("checksum", models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="ScrapingJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("records_processed", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
            ],
        ),
    ]
