# Generated by Django 5.2.2 on 2025-10-08 00:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scraping", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="basketballstats",
            name="is_demo_data",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="footballstats",
            name="is_demo_data",
            field=models.BooleanField(default=False),
        ),
    ]
