# Generated by Django 5.2.2 on 2025-10-08 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="League",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("abbreviation", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="PlayerStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_id", models.CharField(max_length=100)),
                ("player_name", models.CharField(max_length=255)),
                ("team_name", models.CharField(max_length=100)),
                ("points", models.FloatField()),
                ("rebounds", models.FloatField()),
                ("assists", models.FloatField()),
            ],
            options={
                "verbose_name": "Player Stat",
                "verbose_name_plural": "Player Stats",
                "ordering": ["player_name"],
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("abbreviation", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("full_name", models.CharField(max_length=200)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="espnproxy.team"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("date", models.DateTimeField()),
                ("home_score", models.IntegerField(null=True)),
                ("away_score", models.IntegerField(null=True)),
                (
                    "away_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="away_games",
                        to="espnproxy.team",
                    ),
                ),
                (
                    "home_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="home_games",
                        to="espnproxy.team",
                    ),
                ),
            ],
        ),
    ]
