# Generated by Django 5.2.2 on 2025-10-08 00:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("espnproxy", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="league",
            options={"verbose_name": "League", "verbose_name_plural": "Leagues"},
        ),
    ]
